name: BLEAPER CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: microsoft/setup-msbuild@v1
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Restore Dependencies
        run: nuget restore BLEAPER.sln
      - name: Build x64
        run: msbuild BLEAPER.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x64
      - name: Build x86
        run: msbuild BLEAPER.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x86
